file_format: "1"
id: tukon
name: Tukon
type: shield
# url: https://github.com/foostan/crkbd/
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  # - display
  # - rgb backlight
siblings:
  - tukon_left
  - tukon_right